# Generated by Django 3.0.8 on 2020-07-29 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20200728_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollquestion',
            name='question',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
