# Generated by Django 3.0.8 on 2020-08-05 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_comment_voteentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polloption',
            name='option',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
