# Generated by Django 3.0.8 on 2020-08-06 13:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20200805_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollquestion',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
