# Generated by Django 3.0.8 on 2020-09-08 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_pollquestion_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='voteentry',
            name='voted_modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='voteentry',
            name='voted_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
