# Generated by Django 3.0.8 on 2020-09-09 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20200908_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollquestion',
            name='close',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
