# Generated by Django 3.0.8 on 2020-10-14 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_auto_20200911_1544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pollquestion',
            name='tag',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
